apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: guestbook-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

